version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-mongo:/data/db
  postgres:
    image: postgres:15.0
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  data-mongo:
  data-postgres:
